name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: corretto
        java-version: 17
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
    - name: Add label
      uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["automerge"]
          })